const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const User = require('../models/User');
const Order = require('../models/Order');
const { generateOTP } = require('../utils/helpers');
const { sendOTPEmail } = require('../services/emailService');
const JWT_SECRET = process.env.JWT_SECRET || 'natura_botanica_super_secret_key_123';

exports.signup = async (req, res) => { try { const { name, username, email, password } = req.body; if (!name || !username || !email || !password) return res.status(400).json({ error: 'All fields required' }); if (password.length < 8 || password.length > 30) return res.status(400).json({ error: 'Password must be 8-30 chars' }); if (await User.findOne({ $or: [{ email }, { username }] })) return res.status(400).json({ error: 'Email/Username exists' }); const salt = await bcrypt.genSalt(10); const hashedPassword = await bcrypt.hash(password, salt); const otp = generateOTP(); const user = new User({ name, username, email, password: hashedPassword, verificationCode: otp, verificationExpires: new Date(Date.now() + 10 * 60 * 1000) }); await user.save(); await sendOTPEmail(email, name, otp); res.status(201).json({ success: true, message: 'Signup successful! Check email for OTP.' }); } catch (e) { res.status(500).json({ error: e.message }); } };
exports.signin = async (req, res) => { try { const { login, password } = req.body; if (!login || !password) return res.status(400).json({ error: 'Missing fields' }); const user = await User.findOne({ $or: [{ email: login }, { username: login }] }); if (!user) return res.status(400).json({ error: 'Invalid credentials' }); const isMatch = await bcrypt.compare(password, user.password); if (!isMatch) return res.status(400).json({ error: 'Invalid credentials' }); const token = jwt.sign({ id: user._id, email: user.email, isVerified: user.isVerified }, JWT_SECRET, { expiresIn: '7d' }); res.json({ success: true, token, user: { id: user._id, name: user.name, username: user.username, email: user.email, isVerified: user.isVerified, cart: user.cart } }); } catch (e) { res.status(500).json({ error: e.message }); } };
exports.verifyOTP = async (req, res) => { try { const { email, code } = req.body; const user = await User.findOne({ email }); if (!user) return res.status(400).json({ error: 'User not found' }); if (user.isVerified) return res.status(400).json({ error: 'Already verified' }); if (user.verificationCode !== code) return res.status(400).json({ error: 'Invalid code' }); if (user.verificationExpires < new Date()) return res.status(400).json({ error: 'Code expired' }); user.isVerified = true; user.verificationCode = undefined; user.verificationExpires = undefined; await user.save(); const token = jwt.sign({ id: user._id, email: user.email, isVerified: true }, JWT_SECRET, { expiresIn: '7d' }); res.json({ success: true, message: 'Verified!', token, user: { id: user._id, name: user.name, username: user.username, email: user.email, isVerified: true, cart: user.cart } }); } catch (e) { res.status(500).json({ error: e.message }); } };
exports.resendOTP = async (req, res) => { try { const { email } = req.body; const user = await User.findOne({ email }); if (!user) return res.status(400).json({ error: 'User not found' }); if (user.isVerified) return res.status(400).json({ error: 'Already verified' }); const otp = generateOTP(); user.verificationCode = otp; user.verificationExpires = new Date(Date.now() + 10 * 60 * 1000); await user.save(); await sendOTPEmail(email, user.name, otp); res.json({ success: true, message: 'New OTP sent.' }); } catch (e) { res.status(500).json({ error: e.message }); } };
exports.getMe = async (req, res) => { try { const user = await User.findById(req.user.id).select('-password -verificationCode -verificationExpires'); if (!user) return res.status(404).json({ error: 'Not found' }); res.json(user); } catch (e) { res.status(500).json({ error: e.message }); } };
exports.syncCart = async (req, res) => { try { if (!req.user.isVerified) return res.status(403).json({ error: 'Verify email first' }); const user = await User.findById(req.user.id); const localCart = req.body.cart; if (!localCart || !Array.isArray(localCart)) return res.status(400).json({ error: 'Invalid cart' }); let dbCart = [...user.cart]; for (const localItem of localCart) { const existingIndex = dbCart.findIndex(i => i.id === localItem.id && i.unit === localItem.unit && i.form === localItem.form); if (existingIndex >= 0) { dbCart[existingIndex].qty += localItem.qty; } else { dbCart.push(localItem); } } user.cart = dbCart; await user.save(); res.json({ success: true, cart: user.cart }); } catch (e) { res.status(500).json({ error: e.message }); } };
exports.getMyOrders = async (req, res) => { try { const orders = await Order.find({ 'clientDetails.email': req.user.email }).sort({ timestamp: -1 }); res.json(orders); } catch (e) { res.status(500).json({ error: e.message }); } };
exports.getUsers = async (req, res) => { try { const users = await User.find().sort({ _id: -1 }).select('-password -verificationCode -verificationExpires'); res.json({ success: true, users }); } catch (e) { res.status(500).json({ success: false, error: e.message }); } };
exports.deleteUser = async (req, res) => { try { await User.findByIdAndDelete(req.params.id); res.json({ success: true }); } catch (e) { res.status(500).json({ success: false }); } };
