const Order = require('../models/Order');
const Product = require('../models/Product');
const { validateOrder } = require('../utils/helpers');
const { sendClientEmail, sendAdminAlert } = require('../services/emailService');
const STOCK_DEDUCT_STATUSES = ['Completed', 'Success', 'Shipping'];

exports.createOrder = async (req, res) => { try { const errors = validateOrder(req.body); if (errors.length > 0) return res.status(400).json({ success: false, errors }); req.body.clientDetails.name = req.body.clientDetails.name.trim().substring(0, 100); req.body.clientDetails.email = req.body.clientDetails.email.trim().toLowerCase(); req.body.clientDetails.phone = req.body.clientDetails.phone.trim().substring(0, 20); const savedOrder = await new Order({ ...req.body, order_state: 'Pending' }).save(); await sendAdminAlert(savedOrder._id, req.body); res.status(201).json({ success: true, orderId: savedOrder._id }); } catch (e) { res.status(500).json({ success: false, error: 'Server error' }); } };
exports.updateStatus = async (req, res) => { try { const { id, status } = req.body; const order = await Order.findOne({ _id: id }); if (!order) return res.status(404).json({ success: false }); const wasDeducted = STOCK_DEDUCT_STATUSES.includes(order.status); const shouldDeduct = STOCK_DEDUCT_STATUSES.includes(status); await Order.updateOne({ _id: id }, { status, emailStatus: 'Queue' }); if (shouldDeduct && !wasDeducted) { for (const item of (order.items || [])) await Product.updateOne({ id: item.id }, { $inc: { stock: -(parseInt(item.qty) || 1) } }); } else if (!shouldDeduct && wasDeducted) { for (const item of (order.items || [])) await Product.updateOne({ id: item.id }, { $inc: { stock: (parseInt(item.qty) || 1) } }); } let emailStat = 'Queue'; if (order.clientDetails?.email?.includes('@')) { emailStat = await sendClientEmail(order.clientDetails.email, order.clientDetails.name, id, status) ? 'Sent' : 'Failed'; await Order.updateOne({ _id: id }, { emailStatus: emailStat }); } res.json({ success: true, emailStatus: emailStat }); } catch (e) { res.status(500).json({ success: false, emailStatus: 'Failed' }); } };
exports.updateOrderState = async (req, res) => { try { const { id, state } = req.body; if (!id || !state) return res.status(400).json({ success: false }); await Order.updateOne({ _id: id }, { $set: { order_state: state } }); res.json({ success: true }); } catch (e) { res.status(500).json({ success: false }); } };
exports.deleteOrder = async (req, res) => { try { await Order.findByIdAndDelete(req.params.id); res.json({ success: true }); } catch (e) { res.status(500).json({ success: false }); } };
exports.deleteOrders = async (req, res) => { try { await Order.deleteMany({ _id: { $in: req.body.ids } }); res.json({ success: true }); } catch (e) { res.status(500).json({ success: false }); } };
exports.viewOrdersData = async (req, res) => { try { const orders = await Order.find().sort({ timestamp: -1 }).limit(100); res.json({ success: true, orders, count: orders.length }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } };