const Product = require('../models/Product');
const { syncProductsToDB, syncDBToFile, syncFileToDB } = require('../services/syncService');

exports.getProducts = async (req, res) => { try { const products = await Product.find().sort({ id: 1 }).lean(); res.json(products.map(({ _id, __v, ...rest }) => rest)); } catch (e) { res.status(500).json({ error: e.message }); } };
exports.getProductById = async (req, res) => { try { const product = await Product.findOne({ id: Number(req.params.id) }).lean(); if (!product) return res.status(404).json({ error: 'Not found' }); const { _id, __v, ...rest } = product; res.json(rest); } catch (e) { res.status(500).json({ error: e.message }); } };
exports.createProduct = async (req, res) => { try { const { id, name, price } = req.body; if (!id || !name || price === undefined) return res.status(400).json({ error: 'Required' }); if (await Product.findOne({ id })) return res.status(409).json({ error: 'Exists' }); const p = new Product({ ...req.body, stock: req.body.stock ?? 100 }); await p.save(); await syncDBToFile(); res.status(201).json({ success: true }); } catch (e) { res.status(500).json({ error: e.message }); } };
exports.updateProduct = async (req, res) => { try { const updateData = { ...req.body }; if (req.body.stock === undefined) delete updateData.stock; await Product.updateOne({ id: Number(req.params.id) }, { $set: updateData }); await syncDBToFile(); res.json({ success: true }); } catch (e) { res.status(500).json({ error: e.message }); } };
exports.deleteProduct = async (req, res) => { try { const result = await Product.deleteOne({ id: Number(req.params.id) }); if (result.deletedCount === 0) return res.status(404).json({ error: 'Not found' }); await syncDBToFile(); res.json({ success: true }); } catch (e) { res.status(500).json({ error: e.message }); } };
exports.bulkProducts = async (req, res) => { try { if (!Array.isArray(req.body.products)) return res.status(400).json({ error: 'Array required' }); const result = await syncProductsToDB(req.body.products, { removeOrphans: false }); await syncDBToFile(); res.json({ success: true, ...result }); } catch (e) { res.status(500).json({ error: e.message }); } };
exports.seedProducts = async (req, res) => { try { await Product.deleteMany({}); await Product.insertMany(require('../products.json')); res.json({ success: true }); } catch (e) { res.status(500).send(e.message); } };
exports.syncProducts = async (req, res) => { try { const result = await syncFileToDB({ removeOrphans: true }); res.json({ success: true, ...result }); } catch (e) { res.status(500).json({ error: e.message }); } };
exports.seedStock = async (req, res) => { try { await Product.updateMany({}, { $set: { stock: 100 } }); res.send('Stocks reset'); } catch (e) { res.status(500).send(e.message); } };
exports.updateStock = async (req, res) => { try { await Product.updateOne({ id: req.body.id }, { $set: { stock: req.body.stock } }); await syncDBToFile(); res.json({ success: true }); } catch (e) { res.status(500).json({ success: false }); } };
exports.manageStockPage = async (req, res) => { try { const products = await Product.find().sort({ id: 1 }); let rows = products.map(p => { const s = p.stock || 0; let badge = s === 0 ? '<span style="color:#b91c1c">Out</span>' : s <= 10 ? '<span style="color:#c2410c">Low</span>' : '<span style="color:#15803d">In Stock</span>'; return `<tr><td><strong>${p.name}</strong></td><td>${p.catLabel}</td><td>${badge} (${s})</td><td><input type="number" id="s-${p.id}" value="${s}" min="0"></td><td><button onclick="save(${p.id})">Save</button></td></tr>`; }).join(''); res.send(`<html><body><table border="1">${rows}</table><script>async function save(id){const v=document.getElementById('s-'+id).value; await fetch('/api/update-stock',{method:'PUT',headers:{'Content-Type':'application/json','Authorization':'${req.headers['authorization']}'},body:JSON.stringify({id,stock:v})}); location.reload();}</script></body></html>`); } catch (e) { res.status(500).send('Error'); } };